INSERT INTO dms.users(username, password, email, first_name, last_name) VALUES('admin','21232f297a57a5a743894a0e4a801fc3','admin@admin.de','admin','admin');
INSERT INTO dms.user_settings(user_id, setting_key, setting_value) VALUES(1,'language_id',1);
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Andorra','AD','AND','20');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Vereinigte Arabische Emirate','AE','ARE','784');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Afghanistan','AF','AFG','4');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Antigua und Barbuda','AG','ATG','28');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Anguilla','AI','AIA','660');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Albanien','AL','ALB','8');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Armenien','AM','ARM','51');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Angola','AO','AGO','24');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Antarktis','AQ','ATA','10');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Argentinien','AR','ARG','32');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Amerikanisch Samoa','AS','ASM','16');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Österreich','AT','AUT','40');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Australien','AU','AUS','36');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Aruba','AW','ABW','533');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Åland Inseln','AX','ALA','248');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Aserbaidschan','AZ','AZE','31');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Bosnien und Herzegowin','BA','BIH','70');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Barbados','BB','BRB','52');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Bangladesch','BD','BGD','50');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Belgien','BE','BEL','56');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Burkina Faso','BF','BFA','854');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Bulgarien','BG','BGR','100');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Bahrain','BH','BHR','48');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Burundi','BI','BDI','108');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Benin','BJ','BEN','204');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('St. Barthélemy','BL','BLM','652');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Bermuda','BM','BMU','60');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Brunei Darussalam','BN','BRN','96');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Bolivien','BO','BOL','68');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Karibische Niederlande','BQ','BES','535');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Brasilien','BR','BRA','76');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Bahamas','BS','BHS','44');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Bhutan','BT','BTN','64');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Bouvetinsel','BV','BVT','74');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Botsuana','BW','BWA','72');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Weißrussland','BY','BLR','112');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Belize','BZ','BLZ','84');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Kanada','CA','CAN','124');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Kokosinseln','CC','CCK','166');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Kongo, Dem. Rep.','CD','COD','180');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Zentralafrikanische Republik','CF','CAF','140');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Kongo','CG','COG','178');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Schweiz','CH','CHE','756');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Côte d´Ivoire','CI','CIV','384');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Cookinseln','CK','COK','184');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Chile','CL','CHL','152');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Kamerun','CM','CMR','120');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('China','CN','CHN','156');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Kolumbien','CO','COL','170');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Costa Rica','CR','CRI','188');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Kuba','CU','CUB','192');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Kap Verde','CV','CPV','132');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Curaçao','CW','CUW','531');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Weihnachtsinsel','CX','CXR','162');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Zypern','CY','CYP','196');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Tschechische Republik','CZ','CZE','203');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Deutschland','DE','DEU','276');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Republik Dschibuti','DJ','DJI','262');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Dänemark','DK','DNK','208');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Dominica','DM','DMA','212');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Dominikanische Republik','DO','DOM','214');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Algerien','DZ','DZA','12');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Ecuador','EC','ECU','218');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Estland','EE','EST','233');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Ägypten','EG','EGY','818');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Westsahara','EH','ESH','732');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Eritrea','ER','ERI','232');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Spanien','ES','ESP','724');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Äthiopien','ET','ETH','231');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Finnland','FI','FIN','246');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Fidschi','FJ','FJI','242');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Falklandinseln','FK','FLK','238');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Mikronesien, Föderierte Staaten von','FM','FSM','583');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Färöer','FO','FRO','234');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Frankreich','FR','FRA','250');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Gabun','GA','GAB','266');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Vereinigtes Königreich','GB','GBR','826');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Grenada','GD','GRD','308');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Georgien','GE','GEO','268');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Französisch Guiana','GF','GUF','254');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Guernsey','GG','GGY','831');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Ghana','GH','GHA','288');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Gibraltar','GI','GIB','292');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Grönland','GL','GRL','304');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Gambia','GM','GMB','270');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Guinea','GN','GIN','324');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Guadeloupe','GP','GLP','312');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Äquatorialguinea','GQ','GNQ','226');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Griechenland','GR','GRC','300');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Südgeorgien und die Südlichen Sandwichinseln','GS','SGS','239');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Guatemala','GT','GTM','320');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Guam','GU','GUM','316');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Guinea-Bissau','GW','GNB','624');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Guyana','GY','GUY','328');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Hong Kong','HK','HKG','344');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Heard Insel und McDonald Inseln','HM','HMD','334');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Honduras','HN','HND','340');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Kroatien','HR','HRV','191');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Haiti','HT','HTI','332');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Ungarn','HU','HUN','348');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Indonesien','ID','IDN','360');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Irland','IE','IRL','372');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Israel','IL','ISR','376');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Isle of Man','IM','IMN','833');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Indien','IN','IND','356');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Britische Territorien im Indischen Ozean','IO','IOT','86');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Irak','IQ','IRQ','368');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Iran, Islam. Rep.','IR','IRN','364');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Island','IS','ISL','352');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Italien','IT','ITA','380');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Jersey','JE','JEY','832');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Jamaika','JM','JAM','388');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Jordanien','JO','JOR','400');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Japan','JP','JPN','392');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Kenia','KE','KEN','404');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Kirgisistan','KG','KGZ','417');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Kambodscha','KH','KHM','116');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Kiribati','KI','KIR','296');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Komoren','KM','COM','174');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('St. Kitts und Nevis','KN','KNA','659');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Korea, Dem. Volksrep.','KP','PRK','408');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Korea, Rep.','KR','KOR','410');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Kosovo','XK','XKX','0');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Kuwait','KW','KWT','414');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Kaimaninseln','KY','CYM','136');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Kasachstan','KZ','KAZ','398');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Laos, Dem. Volksrep.','LA','LAO','418');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Libanon','LB','LBN','422');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('St. Lucia','LC','LCA','662');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Liechtenstein','LI','LIE','438');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Sri Lanka','LK','LKA','144');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Liberia','LR','LBR','430');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Lesotho','LS','LSO','426');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Litauen','LT','LTU','440');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Luxemburg','LU','LUX','442');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Lettland','LV','LVA','428');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Libysch-Arabische Dschamahirija','LY','LBY','434');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Marokko','MA','MAR','504');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Monaco','MC','MCO','492');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Moldau, Rep.','MD','MDA','498');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Montenegro','ME','MNE','499');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('St. Martin','MF','MAF','663');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Madagaskar','MG','MDG','450');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Marshallinseln','MH','MHL','584');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Mazedonien, ehemalige jugoslawische Republik ','MK','MKD','807');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Mali','ML','MLI','466');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Myanmar','MM','MMR','104');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Mongolei','MN','MNG','496');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Macao','MO','MAC','446');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Nördliche Marianen','MP','MNP','580');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Martinique','MQ','MTQ','474');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Mauretanien','MR','MRT','478');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Montserrat','MS','MSR','500');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Malta','MT','MLT','470');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Mauritius','MU','MUS','480');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Malediven','MV','MDV','462');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Malawi','MW','MWI','454');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Mexiko','MX','MEX','484');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Malaysia','MY','MYS','458');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Mosambik','MZ','MOZ','508');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Namibia','NA','NAM','516');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Neukaledonien','NC','NCL','540');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Niger','NE','NER','562');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Norfolk Insel','NF','NFK','574');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Nigeria','NG','NGA','566');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Nicaragua','NI','NIC','558');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Niederlande','NL','NLD','528');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Norwegen','NO','NOR','578');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Nepal','NP','NPL','524');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Nauru','NR','NRU','520');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Niue','NU','NIU','570');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Neuseeland','NZ','NZL','554');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Oman','OM','OMN','512');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Panama','PA','PAN','591');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Peru','PE','PER','604');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Französisch Polynesien','PF','PYF','258');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Papua-Neuguinea','PG','PNG','598');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Philippinen','PH','PHL','608');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Pakistan','PK','PAK','586');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Polen','PL','POL','616');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Saint Pierre und Miquelon','PM','SPM','666');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Pitcairn','PN','PCN','612');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Puerto Rico','PR','PRI','630');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Palästinische Gebiete','PS','PSE','275');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Portugal','PT','PRT','620');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Palau','PW','PLW','585');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Paraguay','PY','PRY','600');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Katar','QA','QAT','634');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Réunion','RE','REU','638');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Rumänien','RO','ROU','642');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Serbien','RS','SRB','688');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Russische Föderation','RU','RUS','643');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Ruanda','RW','RWA','646');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Saudi-Arabien','SA','SAU','682');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Salomonen','SB','SLB','90');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Seychellen','SC','SYC','690');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Sudan','SD','SDN','729');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Südsudan','SS','SSD','728');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Schweden','SE','SWE','752');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Singapur','SG','SGP','702');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Saint Helena','SH','SHN','654');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Slowenien','SI','SVN','705');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Svalbard und Jan Mayen','SJ','SJM','744');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Slowakei','SK','SVK','703');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Sierra Leone','SL','SLE','694');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('San Marino','SM','SMR','674');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Senegal','SN','SEN','686');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Somalia','SO','SOM','706');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Suriname','SR','SUR','740');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('São Tomé und Príncipe','ST','STP','678');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('El Salvador','SV','SLV','222');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Sint Maarten','SX','SXM','534');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Syrien, Arab. Rep.','SY','SYR','760');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Swasiland','SZ','SWZ','748');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Turks- und Caicosinseln','TC','TCA','796');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Tschad','TD','TCD','148');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Französische Südgebiete','TF','ATF','260');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Thailand','TG','TGO','768');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Thailand','TH','THA','764');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Tadschikistan','TJ','TJK','762');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Tokelau','TK','TKL','772');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Timor-Leste','TL','TLS','626');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Turkmenistan','TM','TKM','795');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Tunesien','TN','TUN','788');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Tonga','TO','TON','776');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Türkei','TR','TUR','792');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Trinidad und Tobago','TT','TTO','780');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Tuvalu','TV','TUV','798');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Taiwan','TW','TWN','158');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Tansania, Vereinigte Rep.','TZ','TZA','834');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Ukraine','UA','UKR','804');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Uganda','UG','UGA','800');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('United States Minor Outlying Islands','UM','UMI','581');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Vereinigte Staaten von Amerika','US','USA','840');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Uruguay','UY','URY','858');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Usbekistan','UZ','UZB','860');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Heiliger Stuhl','VA','VAT','336');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('St. Vincent und die Grenadinen','VC','VCT','670');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Venezuela','VE','VEN','862');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Britische Jungferninseln','VG','VGB','92');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Amerikanische Jungferninseln','VI','VIR','850');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Vietnam','VN','VNM','704');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Vanuatu','VU','VUT','548');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Wallis und Futuna','WF','WLF','876');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Samoa','WS','WSM','882');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Jemen','YE','YEM','887');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Mayotte','YT','MYT','175');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Südafrika','ZA','ZAF','710');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Sambia','ZM','ZMB','894');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Simbabwe','ZW','ZWE','716');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Serbien und Montenegro','CS','SCG','891');
INSERT INTO dms.countries(country_name, alpha2, alpha3, alphanum) VALUES('Niederländische Antillen','AN','ANT','530');
INSERT INTO dms.account_types(type_name) VALUES('Privat');
INSERT INTO dms.account_types(type_name) VALUES('Staatl. Behörden');
INSERT INTO dms.account_types(type_name) VALUES('Einzelhandel');
INSERT INTO dms.account_types(type_name) VALUES('Internet');
INSERT INTO dms.account_types(type_name) VALUES('Einzelperson');
INSERT INTO dms.account_types(type_name) VALUES('Werkstatt/Reparateur');
INSERT INTO dms.account_types(type_name) VALUES('Verkehrsgesellschaft');
INSERT INTO dms.account_types(type_name) VALUES('Hardwareanbieter');
INSERT INTO dms.account_types(type_name) VALUES('Softwareanbieter');
INSERT INTO dms.account_types(type_name) VALUES('Autohaus');
INSERT INTO dms.account_types(type_name) VALUES('Sonstiges');
INSERT INTO dms.retention_periods(period_name, max_time_in_days) VALUES('1 Jahr', 365);
INSERT INTO dms.retention_periods(period_name, max_time_in_days) VALUES('2 Jahre', 730);
INSERT INTO dms.retention_periods(period_name, max_time_in_days) VALUES('3 Jahre', 1095);
INSERT INTO dms.retention_periods(period_name, max_time_in_days) VALUES('4 Jahre', 1460);
INSERT INTO dms.retention_periods(period_name, max_time_in_days) VALUES('5 Jahre', 1825);
INSERT INTO dms.retention_periods(period_name, max_time_in_days) VALUES('6 Jahre', 2190);
INSERT INTO dms.retention_periods(period_name, max_time_in_days) VALUES('7 Jahre', 2555);
INSERT INTO dms.retention_periods(period_name, max_time_in_days) VALUES('8 Jahre', 2920);
INSERT INTO dms.retention_periods(period_name, max_time_in_days) VALUES('9 Jahre', 3285);
INSERT INTO dms.retention_periods(period_name, max_time_in_days) VALUES('10 Jahre', 3650);
INSERT INTO dms.document_types(type_name, default_retention_period_id) VALUES('Auftragsbestätigung',6);
INSERT INTO dms.document_types(type_name, default_retention_period_id) VALUES('Rechnung',6);
INSERT INTO dms.document_types(type_name, default_retention_period_id) VALUES('Garantie/Gewährleistungs-Unterlagen',10);
INSERT INTO dms.document_types(type_name, default_retention_period_id) VALUES('Lizenz',10);
INSERT INTO dms.document_types(type_name, default_retention_period_id) VALUES('Zeiterfassung',10);
INSERT INTO dms.document_types(type_name, default_retention_period_id) VALUES('Steuer',10);
INSERT INTO dms.document_types(type_name, default_retention_period_id) VALUES('Gehaltszettel',10);
INSERT INTO dms.document_types(type_name, default_retention_period_id) VALUES('Ausweis',10);
INSERT INTO dms.document_types(type_name, default_retention_period_id) VALUES('Vertrag',10);
INSERT INTO dms.document_types(type_name, default_retention_period_id) VALUES('Stornierung',10);
INSERT INTO dms.document_types(type_name, default_retention_period_id) VALUES('Notiz',10);
INSERT INTO dms.languages(language_name) VALUES('English');
INSERT INTO dms.languages(language_name) VALUES('Deutsch');
